name: feinsum-eval-env
channels:
- conda-forge
- nodefaults
dependencies:
- python=3
- islpy
- numpy
- jax
- jaxlib=*=*cuda*
- ocl-icd
- pip:
  - "loopy"
  - "pyopencl"
  - "arraycontext"
  - "feinsum"